--TABLA

CREATE TABLE PLAYER
(
    PLAYER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER(3) NOT NULL,
    TEAM VARCHAR2(100) NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE
);


INSERT INTO PLAYER(NAME, AGE, TEAM)
VALUES('Lionel Messi',38,'Inter Miami');

INSERT INTO PLAYER(NAME, AGE, TEAM)
VALUES('Cristiano Ronaldo',41,'Al Nassr');

INSERT INTO PLAYER(NAME, AGE, TEAM)
VALUES('Kylian Mbappé',28,'Real Madrid');

-----------------------------------------------}
CREATE OR REPLACE PACKAGE BODY PKG_PLAYER AS

    PROCEDURE GET_ALL
    (
        P_CURSOR OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT
                PLAYER_ID,
                NAME,
                AGE,
                TEAM,
                CREATED_DATE,
                UPDATED_DATE
            FROM PLAYER
            ORDER BY PLAYER_ID;
    END GET_ALL;


    PROCEDURE GET_BY_ID
    (
        P_PLAYER_ID IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
    IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT
                PLAYER_ID,
                NAME,
                AGE,
                TEAM,
                CREATED_DATE,
                UPDATED_DATE
            FROM PLAYER
            WHERE PLAYER_ID = P_PLAYER_ID;
    END GET_BY_ID;


    PROCEDURE INSERT_PLAYER
    (
        P_NAME IN VARCHAR2,
        P_AGE IN NUMBER,
        P_TEAM IN VARCHAR2
    )
    IS
    BEGIN
        INSERT INTO PLAYER
        (
            NAME,
            AGE,
            TEAM
        )
        VALUES
        (
            P_NAME,
            P_AGE,
            P_TEAM
        );
    END INSERT_PLAYER;


    PROCEDURE UPDATE_PLAYER
    (
        P_PLAYER_ID IN NUMBER,
        P_NAME IN VARCHAR2,
        P_AGE IN NUMBER,
        P_TEAM IN VARCHAR2
    )
    IS
    BEGIN
        UPDATE PLAYER
        SET
            NAME = P_NAME,
            AGE = P_AGE,
            TEAM = P_TEAM,
            UPDATED_DATE = SYSDATE
        WHERE PLAYER_ID = P_PLAYER_ID;
    END UPDATE_PLAYER;


    PROCEDURE DELETE_PLAYER
    (
        P_PLAYER_ID IN NUMBER
    )
    IS
    BEGIN
        DELETE FROM PLAYER
        WHERE PLAYER_ID = P_PLAYER_ID;
    END DELETE_PLAYER;

END PKG_PLAYER;

-------------------------------------------------------------
